spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      defer-datasource-initialization: ture

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 754639550621-hsaht0plhjc6hqbao3rs3nj2lqh78ofg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: a193344@gmail.com
  secret_key: study-springboot
